export default {
   plus: { valueNumber: true },
   minus: { dataNullOrValueNumber: true },
   multiply: { valueNumber: true },
   divide: { valueNumber: true },
   factorial: { valueNumber: true },
   degree: { dataNullOrValueNumber: false },
   sqrt: { dataNullOrValueNumber: false },
   dot: { valueNumber: true },
   setNumber: {},
   change_sign: { valueNumber: true },
   percent: { valueNumber: true },
   M_MINUS: { dataLength_1: 1, valueNumber: true, isMemory: true },
   M_PLUS: { dataLength_1: 1, valueNumber: true, isMemory: true },
   MR: {},
   MC: {},
   cancel: {},
   equal: { dataLength_3: true },
}
