import getElById from '../utils/getElById'
import calculator from './core/functional'

const {
   setValue,
   clear,
   MC,
   MR,
   M_MINUS,
   M_PLUS,
   cancel,
   factorial,
   change_sign,
   minus,
   percent,
   multiply,
   sum,
   dot,
   equal,
   division,
   sqrt,
   degree,
   ten_x,
   _1_x,
} = calculator.getActions()

export const Buttons = {
   value_0: { el: getElById('value_0'), handler: setValue(0) },
   value_1: { el: getElById('value_1'), handler: setValue(1) },
   value_2: { el: getElById('value_2'), handler: setValue(2) },
   value_3: { el: getElById('value_3'), handler: setValue(3) },
   value_4: { el: getElById('value_4'), handler: setValue(4) },
   value_5: { el: getElById('value_5'), handler: setValue(5) },
   value_6: { el: getElById('value_6'), handler: setValue(6) },
   value_7: { el: getElById('value_7'), handler: setValue(7) },
   value_8: { el: getElById('value_8'), handler: setValue(8) },
   value_9: { el: getElById('value_9'), handler: setValue(9) },
   clear: { el: getElById('clear'), handler: clear },
   change_sign: { el: getElById('change_sign'), handler: change_sign },
   percent: { el: getElById('percent'), handler: percent },
   division: { el: getElById('division'), handler: division },
   multiply: { el: getElById('multiply'), handler: multiply },
   minus: { el: getElById('minus'), handler: minus },
   sum: { el: getElById('sum'), handler: sum },
   dot: { el: getElById('dot'), handler: dot },
   MC: { el: getElById('MC'), handler: MC },
   MR: { el: getElById('MR'), handler: MR },
   M_MINUS: { el: getElById('M_MINUS'), handler: M_MINUS },
   M_PLUS: { el: getElById('M_PLUS'), handler: M_PLUS },
   cancel: { el: getElById('cancel'), handler: cancel },
   x_2: { el: getElById('x_2'), handler: degree(2) },
   x_3: { el: getElById('x_3'), handler: degree(3) },
   x_y: { el: getElById('x_y'), handler: degree() },
   sqrt_2: { el: getElById('sqrt_2'), handler: sqrt(2) },
   sqrt_3: { el: getElById('sqrt_3'), handler: sqrt(3) },
   sqrt_y: { el: getElById('sqrt_y'), handler: sqrt() },
   _10_x: { el: getElById('_10_x'), handler: ten_x },
   _1_x: { el: getElById('_1_x'), handler: _1_x },
   factorial: { el: getElById('factorial'), handler: factorial },
   equal: { el: getElById('equal'), handler: equal },
}
